name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
#          npm run test --if-present

      - name: Zip artifacts for deployment
        run: |
          echo ${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}/dist/apps/avans-code-web/browser && zip ${GITHUB_WORKSPACE}/avans-code-web.zip ./* -r
          cd ${GITHUB_WORKSPACE}/dist/apps/avans-code-api/ && zip ${GITHUB_WORKSPACE}/avans-code-api.zip ./* -r

      - name: Upload frontend artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: avans-code-web
          path: avans-code-web.zip

      - name: Upload backend artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: avans-code-api
          path: avans-code-api.zip


  deploy-frontend-app:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: avans-code-web

      - name: Unzip artifact
        run: unzip avans-code-web.zip -d avans-code-web

      - name: Deploy to static azure web app
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.ANGULAR_PUBLISHTOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          skip_app_build: true
          action: "upload"
          app_location: "avans-code-web"

  deploy-backend-api:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: avans-code-api

      - name: Unzip artifact
        run: unzip avans-code-api.zip

      - name: Install dependencies
        run: npm install

      - name: 'Deploy to Azure'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'avans-code'
          slot-name: 'Production'
          publish-profile: ${{ secrets.NEXTJS_PUBLISHPROFILE }}
          package: .
